name: push_notifications_demo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.

environment: 
  sdk: '>=2.18.4 <3.0.0'

#  old dependencies
#  firebase_core: ^1.20.0
#  firebase_messaging: ^12.0.1
#  flutter_local_notifications: ^9.7.0

dependencies:
  after_layout: ^1.2.0
  app_settings: ^4.2.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0
  get: ^4.6.5
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  keyboard_dismisser: ^3.0.0
  modal_bottom_sheet: ^2.1.2
  overlay_support: ^2.1.0
  permission_handler: ^10.2.0
  timezone: ^0.9.1
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
